//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThucTap.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int Discount_ID { get; set; }
        public string Discount_name { get; set; }
        public Nullable<bool> Discount_allProduct { get; set; }
        public Nullable<int> Discount_Product { get; set; }
        public Nullable<System.DateTime> Discount_DateStart { get; set; }
        public Nullable<System.DateTime> Discount_DateEnd { get; set; }
        public Nullable<int> Discount_Per { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
