//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThucTap.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import_Info
    {
        public int Import_ID { get; set; }
        public int Ingredient_ID { get; set; }
        public int II_Quantity { get; set; }
    
        public virtual Import Import { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
