//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThucTap.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.Import_Info = new HashSet<Import_Info>();
        }
    
        public int Ingredient_ID { get; set; }
        public string Ingredient_Name { get; set; }
        public string Ingredient_Unit { get; set; }
        public long Ingredient_PriceImport { get; set; }
        public bool Ingredient_isActive { get; set; }
        public Nullable<double> Ingredient_Reserved { get; set; }
        public byte[] Ingredient_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Import_Info> Import_Info { get; set; }
    }
}
