//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThucTap.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TheLightCoffeeEntities : DbContext
    {
        public TheLightCoffeeEntities()
            : base("name=TheLightCoffeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Bill_Info> Bill_Info { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<DBTable> DBTables { get; set; }
        public virtual DbSet<Import> Imports { get; set; }
        public virtual DbSet<Surcharge> Surcharges { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Import_Info> Import_Info { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
    
        public virtual ObjectResult<exportBillTakeAway_Result> exportBillTakeAway(Nullable<int> billID)
        {
            var billIDParameter = billID.HasValue ?
                new ObjectParameter("BillID", billID) :
                new ObjectParameter("BillID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<exportBillTakeAway_Result>("exportBillTakeAway", billIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> TotalMoney(Nullable<int> billID)
        {
            var billIDParameter = billID.HasValue ?
                new ObjectParameter("BillID", billID) :
                new ObjectParameter("BillID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("TotalMoney", billIDParameter);
        }
    
        public virtual ObjectResult<exportBillNoTakeAway_Result> exportBillNoTakeAway(Nullable<int> billID)
        {
            var billIDParameter = billID.HasValue ?
                new ObjectParameter("BillID", billID) :
                new ObjectParameter("BillID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<exportBillNoTakeAway_Result>("exportBillNoTakeAway", billIDParameter);
        }
    
        public virtual int addSurchange(Nullable<int> billid, Nullable<int> surid)
        {
            var billidParameter = billid.HasValue ?
                new ObjectParameter("billid", billid) :
                new ObjectParameter("billid", typeof(int));
    
            var suridParameter = surid.HasValue ?
                new ObjectParameter("surid", surid) :
                new ObjectParameter("surid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addSurchange", billidParameter, suridParameter);
        }
    
        public virtual int removeSurchange(Nullable<int> billid, Nullable<int> surid)
        {
            var billidParameter = billid.HasValue ?
                new ObjectParameter("billid", billid) :
                new ObjectParameter("billid", typeof(int));
    
            var suridParameter = surid.HasValue ?
                new ObjectParameter("surid", surid) :
                new ObjectParameter("surid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("removeSurchange", billidParameter, suridParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> checkSurcharge(Nullable<int> billid)
        {
            var billidParameter = billid.HasValue ?
                new ObjectParameter("billid", billid) :
                new ObjectParameter("billid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("checkSurcharge", billidParameter);
        }
    
        public virtual int removeFullSurchange(Nullable<int> billid)
        {
            var billidParameter = billid.HasValue ?
                new ObjectParameter("billid", billid) :
                new ObjectParameter("billid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("removeFullSurchange", billidParameter);
        }
    
        public virtual ObjectResult<exportIImport_Result> exportIImport(Nullable<int> importID)
        {
            var importIDParameter = importID.HasValue ?
                new ObjectParameter("ImportID", importID) :
                new ObjectParameter("ImportID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<exportIImport_Result>("exportIImport", importIDParameter);
        }
    
        public virtual ObjectResult<exportDate_Result> exportDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<exportDate_Result>("exportDate");
        }
    }
}
