//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThucTap.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_ID { get; set; }
        public string Payment_name { get; set; }
        public Nullable<System.DateTime> Payment_time { get; set; }
        public string Payment_Staff { get; set; }
        public Nullable<long> Payment_money { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
