namespace DoAnThucTap.GUI
{
    partial class Product_GUI
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Product_GUI));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.top = new Bunifu.UI.WinForms.BunifuPanel();
            this.lblData = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnBack = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.pnlMain = new Bunifu.UI.WinForms.BunifuPanel();
            this.bottomLeft = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.btnFood = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnMoreDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnYaour = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnIce = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnVitamin = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnJuice = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnMilkTea = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCoffee = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTea = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.txtFind100 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtFind50 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnFind100 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.btnFind50 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.pnlListProduct = new System.Windows.Forms.FlowLayoutPanel();
            this.top.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.pnlMain.SuspendLayout();
            this.bottomLeft.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.bunifuPanel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 0;
            this.bunifuElipse1.TargetControl = this;
            // 
            // top
            // 
            this.top.BackgroundColor = System.Drawing.Color.Teal;
            this.top.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("top.BackgroundImage")));
            this.top.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.top.BorderColor = System.Drawing.Color.Teal;
            this.top.BorderRadius = 0;
            this.top.BorderThickness = 1;
            this.top.Controls.Add(this.lblData);
            this.top.Controls.Add(this.btnBack);
            this.top.Dock = System.Windows.Forms.DockStyle.Top;
            this.top.Location = new System.Drawing.Point(0, 0);
            this.top.Name = "top";
            this.top.ShowBorders = true;
            this.top.Size = new System.Drawing.Size(1567, 53);
            this.top.TabIndex = 1;
            // 
            // lblData
            // 
            this.lblData.AllowParentOverrides = false;
            this.lblData.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lblData.AutoEllipsis = false;
            this.lblData.AutoSize = false;
            this.lblData.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblData.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblData.Font = new System.Drawing.Font("Times New Roman", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblData.ForeColor = System.Drawing.Color.White;
            this.lblData.Location = new System.Drawing.Point(56, 3);
            this.lblData.Name = "lblData";
            this.lblData.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblData.Size = new System.Drawing.Size(1508, 47);
            this.lblData.TabIndex = 1;
            this.lblData.Text = "Thực đơn";
            this.lblData.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblData.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnBack
            // 
            this.btnBack.ActiveImage = null;
            this.btnBack.AllowAnimations = true;
            this.btnBack.AllowBuffering = false;
            this.btnBack.AllowToggling = false;
            this.btnBack.AllowZooming = true;
            this.btnBack.AllowZoomingOnFocus = false;
            this.btnBack.BackColor = System.Drawing.Color.Teal;
            this.btnBack.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBack.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnBack.ErrorImage")));
            this.btnBack.FadeWhenInactive = false;
            this.btnBack.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnBack.Image = global::DoAnThucTap.Properties.Resources.left_arrow;
            this.btnBack.ImageActive = null;
            this.btnBack.ImageLocation = null;
            this.btnBack.ImageMargin = 0;
            this.btnBack.ImageSize = new System.Drawing.Size(46, 46);
            this.btnBack.ImageZoomSize = new System.Drawing.Size(47, 47);
            this.btnBack.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnBack.InitialImage")));
            this.btnBack.Location = new System.Drawing.Point(3, 3);
            this.btnBack.Name = "btnBack";
            this.btnBack.Rotation = 0;
            this.btnBack.ShowActiveImage = true;
            this.btnBack.ShowCursorChanges = true;
            this.btnBack.ShowImageBorders = false;
            this.btnBack.ShowSizeMarkers = false;
            this.btnBack.Size = new System.Drawing.Size(47, 47);
            this.btnBack.TabIndex = 0;
            this.btnBack.ToolTipText = "";
            this.btnBack.WaitOnLoad = false;
            this.btnBack.Zoom = 0;
            this.btnBack.ZoomSpeed = 10;
            this.btnBack.Click += new System.EventHandler(this.btnBack_Click);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 0;
            this.bunifuPanel1.BorderThickness = 0;
            this.bunifuPanel1.Controls.Add(this.pnlMain);
            this.bunifuPanel1.Controls.Add(this.bottomLeft);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 53);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = false;
            this.bunifuPanel1.Size = new System.Drawing.Size(1567, 676);
            this.bunifuPanel1.TabIndex = 2;
            // 
            // pnlMain
            // 
            this.pnlMain.BackgroundColor = System.Drawing.Color.White;
            this.pnlMain.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlMain.BackgroundImage")));
            this.pnlMain.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlMain.BorderColor = System.Drawing.Color.ForestGreen;
            this.pnlMain.BorderRadius = 0;
            this.pnlMain.BorderThickness = 1;
            this.pnlMain.Controls.Add(this.pnlListProduct);
            this.pnlMain.Controls.Add(this.bunifuPanel2);
            this.pnlMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlMain.Location = new System.Drawing.Point(209, 0);
            this.pnlMain.Name = "pnlMain";
            this.pnlMain.ShowBorders = true;
            this.pnlMain.Size = new System.Drawing.Size(1358, 676);
            this.pnlMain.TabIndex = 2;
            // 
            // bottomLeft
            // 
            this.bottomLeft.BackgroundColor = System.Drawing.Color.White;
            this.bottomLeft.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bottomLeft.BackgroundImage")));
            this.bottomLeft.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bottomLeft.BorderColor = System.Drawing.Color.Transparent;
            this.bottomLeft.BorderRadius = 3;
            this.bottomLeft.BorderThickness = 1;
            this.bottomLeft.Controls.Add(this.bunifuPictureBox1);
            this.bottomLeft.Controls.Add(this.btnFood);
            this.bottomLeft.Controls.Add(this.btnMoreDrink);
            this.bottomLeft.Controls.Add(this.btnYaour);
            this.bottomLeft.Controls.Add(this.btnIce);
            this.bottomLeft.Controls.Add(this.btnVitamin);
            this.bottomLeft.Controls.Add(this.btnJuice);
            this.bottomLeft.Controls.Add(this.btnMilkTea);
            this.bottomLeft.Controls.Add(this.btnCoffee);
            this.bottomLeft.Controls.Add(this.btnTea);
            this.bottomLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this.bottomLeft.Location = new System.Drawing.Point(0, 0);
            this.bottomLeft.Name = "bottomLeft";
            this.bottomLeft.Padding = new System.Windows.Forms.Padding(5);
            this.bottomLeft.ShowBorders = true;
            this.bottomLeft.Size = new System.Drawing.Size(209, 676);
            this.bottomLeft.TabIndex = 1;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 72;
            this.bunifuPictureBox1.Image = global::DoAnThucTap.Properties.Resources.logoquan;
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(32, 503);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(144, 144);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 9;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // btnFood
            // 
            this.btnFood.AllowAnimations = true;
            this.btnFood.AllowMouseEffects = true;
            this.btnFood.AllowToggling = false;
            this.btnFood.AnimationSpeed = 200;
            this.btnFood.AutoGenerateColors = false;
            this.btnFood.AutoRoundBorders = false;
            this.btnFood.AutoSizeLeftIcon = true;
            this.btnFood.AutoSizeRightIcon = true;
            this.btnFood.BackColor = System.Drawing.Color.Transparent;
            this.btnFood.BackColor1 = System.Drawing.Color.Teal;
            this.btnFood.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFood.BackgroundImage")));
            this.btnFood.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFood.ButtonText = "Đồ ăn vặt";
            this.btnFood.ButtonTextMarginLeft = 0;
            this.btnFood.ColorContrastOnClick = 45;
            this.btnFood.ColorContrastOnHover = 45;
            this.btnFood.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnFood.CustomizableEdges = borderEdges1;
            this.btnFood.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFood.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFood.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFood.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFood.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnFood.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnFood.ForeColor = System.Drawing.Color.White;
            this.btnFood.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFood.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFood.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFood.IconMarginLeft = 11;
            this.btnFood.IconPadding = 10;
            this.btnFood.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFood.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFood.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFood.IconSize = 25;
            this.btnFood.IdleBorderColor = System.Drawing.Color.Azure;
            this.btnFood.IdleBorderRadius = 10;
            this.btnFood.IdleBorderThickness = 1;
            this.btnFood.IdleFillColor = System.Drawing.Color.Teal;
            this.btnFood.IdleIconLeftImage = null;
            this.btnFood.IdleIconRightImage = null;
            this.btnFood.IndicateFocus = false;
            this.btnFood.Location = new System.Drawing.Point(8, 448);
            this.btnFood.Name = "btnFood";
            this.btnFood.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFood.OnDisabledState.BorderRadius = 10;
            this.btnFood.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFood.OnDisabledState.BorderThickness = 1;
            this.btnFood.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFood.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFood.OnDisabledState.IconLeftImage = null;
            this.btnFood.OnDisabledState.IconRightImage = null;
            this.btnFood.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnFood.onHoverState.BorderRadius = 10;
            this.btnFood.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFood.onHoverState.BorderThickness = 1;
            this.btnFood.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnFood.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnFood.onHoverState.IconLeftImage = null;
            this.btnFood.onHoverState.IconRightImage = null;
            this.btnFood.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.btnFood.OnIdleState.BorderRadius = 10;
            this.btnFood.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFood.OnIdleState.BorderThickness = 1;
            this.btnFood.OnIdleState.FillColor = System.Drawing.Color.Teal;
            this.btnFood.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnFood.OnIdleState.IconLeftImage = null;
            this.btnFood.OnIdleState.IconRightImage = null;
            this.btnFood.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnFood.OnPressedState.BorderRadius = 10;
            this.btnFood.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFood.OnPressedState.BorderThickness = 1;
            this.btnFood.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnFood.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnFood.OnPressedState.IconLeftImage = null;
            this.btnFood.OnPressedState.IconRightImage = null;
            this.btnFood.Size = new System.Drawing.Size(193, 49);
            this.btnFood.TabIndex = 8;
            this.btnFood.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFood.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFood.TextMarginLeft = 0;
            this.btnFood.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnFood.UseDefaultRadiusAndThickness = true;
            this.btnFood.Click += new System.EventHandler(this.btnFood_Click);
            // 
            // btnMoreDrink
            // 
            this.btnMoreDrink.AllowAnimations = true;
            this.btnMoreDrink.AllowMouseEffects = true;
            this.btnMoreDrink.AllowToggling = false;
            this.btnMoreDrink.AnimationSpeed = 200;
            this.btnMoreDrink.AutoGenerateColors = false;
            this.btnMoreDrink.AutoRoundBorders = false;
            this.btnMoreDrink.AutoSizeLeftIcon = true;
            this.btnMoreDrink.AutoSizeRightIcon = true;
            this.btnMoreDrink.BackColor = System.Drawing.Color.Transparent;
            this.btnMoreDrink.BackColor1 = System.Drawing.Color.Teal;
            this.btnMoreDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnMoreDrink.BackgroundImage")));
            this.btnMoreDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMoreDrink.ButtonText = "Thức uống khác";
            this.btnMoreDrink.ButtonTextMarginLeft = 0;
            this.btnMoreDrink.ColorContrastOnClick = 45;
            this.btnMoreDrink.ColorContrastOnHover = 45;
            this.btnMoreDrink.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnMoreDrink.CustomizableEdges = borderEdges2;
            this.btnMoreDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnMoreDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnMoreDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnMoreDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnMoreDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnMoreDrink.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnMoreDrink.ForeColor = System.Drawing.Color.White;
            this.btnMoreDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMoreDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnMoreDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnMoreDrink.IconMarginLeft = 11;
            this.btnMoreDrink.IconPadding = 10;
            this.btnMoreDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnMoreDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnMoreDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnMoreDrink.IconSize = 25;
            this.btnMoreDrink.IdleBorderColor = System.Drawing.Color.Azure;
            this.btnMoreDrink.IdleBorderRadius = 10;
            this.btnMoreDrink.IdleBorderThickness = 1;
            this.btnMoreDrink.IdleFillColor = System.Drawing.Color.Teal;
            this.btnMoreDrink.IdleIconLeftImage = null;
            this.btnMoreDrink.IdleIconRightImage = null;
            this.btnMoreDrink.IndicateFocus = false;
            this.btnMoreDrink.Location = new System.Drawing.Point(8, 393);
            this.btnMoreDrink.Name = "btnMoreDrink";
            this.btnMoreDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnMoreDrink.OnDisabledState.BorderRadius = 10;
            this.btnMoreDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMoreDrink.OnDisabledState.BorderThickness = 1;
            this.btnMoreDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnMoreDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnMoreDrink.OnDisabledState.IconLeftImage = null;
            this.btnMoreDrink.OnDisabledState.IconRightImage = null;
            this.btnMoreDrink.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnMoreDrink.onHoverState.BorderRadius = 10;
            this.btnMoreDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMoreDrink.onHoverState.BorderThickness = 1;
            this.btnMoreDrink.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnMoreDrink.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnMoreDrink.onHoverState.IconLeftImage = null;
            this.btnMoreDrink.onHoverState.IconRightImage = null;
            this.btnMoreDrink.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.btnMoreDrink.OnIdleState.BorderRadius = 10;
            this.btnMoreDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMoreDrink.OnIdleState.BorderThickness = 1;
            this.btnMoreDrink.OnIdleState.FillColor = System.Drawing.Color.Teal;
            this.btnMoreDrink.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnMoreDrink.OnIdleState.IconLeftImage = null;
            this.btnMoreDrink.OnIdleState.IconRightImage = null;
            this.btnMoreDrink.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnMoreDrink.OnPressedState.BorderRadius = 10;
            this.btnMoreDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMoreDrink.OnPressedState.BorderThickness = 1;
            this.btnMoreDrink.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnMoreDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnMoreDrink.OnPressedState.IconLeftImage = null;
            this.btnMoreDrink.OnPressedState.IconRightImage = null;
            this.btnMoreDrink.Size = new System.Drawing.Size(193, 49);
            this.btnMoreDrink.TabIndex = 7;
            this.btnMoreDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnMoreDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnMoreDrink.TextMarginLeft = 0;
            this.btnMoreDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnMoreDrink.UseDefaultRadiusAndThickness = true;
            this.btnMoreDrink.Click += new System.EventHandler(this.btnMoreDrink_Click);
            // 
            // btnYaour
            // 
            this.btnYaour.AllowAnimations = true;
            this.btnYaour.AllowMouseEffects = true;
            this.btnYaour.AllowToggling = false;
            this.btnYaour.AnimationSpeed = 200;
            this.btnYaour.AutoGenerateColors = false;
            this.btnYaour.AutoRoundBorders = false;
            this.btnYaour.AutoSizeLeftIcon = true;
            this.btnYaour.AutoSizeRightIcon = true;
            this.btnYaour.BackColor = System.Drawing.Color.Transparent;
            this.btnYaour.BackColor1 = System.Drawing.Color.Teal;
            this.btnYaour.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnYaour.BackgroundImage")));
            this.btnYaour.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYaour.ButtonText = "Yaour";
            this.btnYaour.ButtonTextMarginLeft = 0;
            this.btnYaour.ColorContrastOnClick = 45;
            this.btnYaour.ColorContrastOnHover = 45;
            this.btnYaour.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnYaour.CustomizableEdges = borderEdges3;
            this.btnYaour.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnYaour.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnYaour.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnYaour.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnYaour.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnYaour.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnYaour.ForeColor = System.Drawing.Color.White;
            this.btnYaour.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnYaour.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnYaour.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnYaour.IconMarginLeft = 11;
            this.btnYaour.IconPadding = 10;
            this.btnYaour.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnYaour.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnYaour.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnYaour.IconSize = 25;
            this.btnYaour.IdleBorderColor = System.Drawing.Color.Azure;
            this.btnYaour.IdleBorderRadius = 10;
            this.btnYaour.IdleBorderThickness = 1;
            this.btnYaour.IdleFillColor = System.Drawing.Color.Teal;
            this.btnYaour.IdleIconLeftImage = null;
            this.btnYaour.IdleIconRightImage = null;
            this.btnYaour.IndicateFocus = false;
            this.btnYaour.Location = new System.Drawing.Point(8, 338);
            this.btnYaour.Name = "btnYaour";
            this.btnYaour.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnYaour.OnDisabledState.BorderRadius = 10;
            this.btnYaour.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYaour.OnDisabledState.BorderThickness = 1;
            this.btnYaour.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnYaour.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnYaour.OnDisabledState.IconLeftImage = null;
            this.btnYaour.OnDisabledState.IconRightImage = null;
            this.btnYaour.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnYaour.onHoverState.BorderRadius = 10;
            this.btnYaour.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYaour.onHoverState.BorderThickness = 1;
            this.btnYaour.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnYaour.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnYaour.onHoverState.IconLeftImage = null;
            this.btnYaour.onHoverState.IconRightImage = null;
            this.btnYaour.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.btnYaour.OnIdleState.BorderRadius = 10;
            this.btnYaour.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYaour.OnIdleState.BorderThickness = 1;
            this.btnYaour.OnIdleState.FillColor = System.Drawing.Color.Teal;
            this.btnYaour.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnYaour.OnIdleState.IconLeftImage = null;
            this.btnYaour.OnIdleState.IconRightImage = null;
            this.btnYaour.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnYaour.OnPressedState.BorderRadius = 10;
            this.btnYaour.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnYaour.OnPressedState.BorderThickness = 1;
            this.btnYaour.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnYaour.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnYaour.OnPressedState.IconLeftImage = null;
            this.btnYaour.OnPressedState.IconRightImage = null;
            this.btnYaour.Size = new System.Drawing.Size(193, 49);
            this.btnYaour.TabIndex = 6;
            this.btnYaour.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnYaour.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnYaour.TextMarginLeft = 0;
            this.btnYaour.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnYaour.UseDefaultRadiusAndThickness = true;
            this.btnYaour.Click += new System.EventHandler(this.btnYaour_Click);
            // 
            // btnIce
            // 
            this.btnIce.AllowAnimations = true;
            this.btnIce.AllowMouseEffects = true;
            this.btnIce.AllowToggling = false;
            this.btnIce.AnimationSpeed = 200;
            this.btnIce.AutoGenerateColors = false;
            this.btnIce.AutoRoundBorders = false;
            this.btnIce.AutoSizeLeftIcon = true;
            this.btnIce.AutoSizeRightIcon = true;
            this.btnIce.BackColor = System.Drawing.Color.Transparent;
            this.btnIce.BackColor1 = System.Drawing.Color.Teal;
            this.btnIce.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnIce.BackgroundImage")));
            this.btnIce.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIce.ButtonText = "Đá xay";
            this.btnIce.ButtonTextMarginLeft = 0;
            this.btnIce.ColorContrastOnClick = 45;
            this.btnIce.ColorContrastOnHover = 45;
            this.btnIce.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnIce.CustomizableEdges = borderEdges4;
            this.btnIce.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnIce.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnIce.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnIce.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnIce.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnIce.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnIce.ForeColor = System.Drawing.Color.White;
            this.btnIce.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnIce.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnIce.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnIce.IconMarginLeft = 11;
            this.btnIce.IconPadding = 10;
            this.btnIce.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnIce.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnIce.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnIce.IconSize = 25;
            this.btnIce.IdleBorderColor = System.Drawing.Color.Azure;
            this.btnIce.IdleBorderRadius = 10;
            this.btnIce.IdleBorderThickness = 1;
            this.btnIce.IdleFillColor = System.Drawing.Color.Teal;
            this.btnIce.IdleIconLeftImage = null;
            this.btnIce.IdleIconRightImage = null;
            this.btnIce.IndicateFocus = false;
            this.btnIce.Location = new System.Drawing.Point(8, 283);
            this.btnIce.Name = "btnIce";
            this.btnIce.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnIce.OnDisabledState.BorderRadius = 10;
            this.btnIce.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIce.OnDisabledState.BorderThickness = 1;
            this.btnIce.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnIce.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnIce.OnDisabledState.IconLeftImage = null;
            this.btnIce.OnDisabledState.IconRightImage = null;
            this.btnIce.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnIce.onHoverState.BorderRadius = 10;
            this.btnIce.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIce.onHoverState.BorderThickness = 1;
            this.btnIce.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnIce.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnIce.onHoverState.IconLeftImage = null;
            this.btnIce.onHoverState.IconRightImage = null;
            this.btnIce.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.btnIce.OnIdleState.BorderRadius = 10;
            this.btnIce.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIce.OnIdleState.BorderThickness = 1;
            this.btnIce.OnIdleState.FillColor = System.Drawing.Color.Teal;
            this.btnIce.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnIce.OnIdleState.IconLeftImage = null;
            this.btnIce.OnIdleState.IconRightImage = null;
            this.btnIce.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnIce.OnPressedState.BorderRadius = 10;
            this.btnIce.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIce.OnPressedState.BorderThickness = 1;
            this.btnIce.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnIce.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnIce.OnPressedState.IconLeftImage = null;
            this.btnIce.OnPressedState.IconRightImage = null;
            this.btnIce.Size = new System.Drawing.Size(193, 49);
            this.btnIce.TabIndex = 5;
            this.btnIce.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnIce.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnIce.TextMarginLeft = 0;
            this.btnIce.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnIce.UseDefaultRadiusAndThickness = true;
            this.btnIce.Click += new System.EventHandler(this.btnIce_Click);
            // 
            // btnVitamin
            // 
            this.btnVitamin.AllowAnimations = true;
            this.btnVitamin.AllowMouseEffects = true;
            this.btnVitamin.AllowToggling = false;
            this.btnVitamin.AnimationSpeed = 200;
            this.btnVitamin.AutoGenerateColors = false;
            this.btnVitamin.AutoRoundBorders = false;
            this.btnVitamin.AutoSizeLeftIcon = true;
            this.btnVitamin.AutoSizeRightIcon = true;
            this.btnVitamin.BackColor = System.Drawing.Color.Transparent;
            this.btnVitamin.BackColor1 = System.Drawing.Color.Teal;
            this.btnVitamin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnVitamin.BackgroundImage")));
            this.btnVitamin.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVitamin.ButtonText = "Sinh tố";
            this.btnVitamin.ButtonTextMarginLeft = 0;
            this.btnVitamin.ColorContrastOnClick = 45;
            this.btnVitamin.ColorContrastOnHover = 45;
            this.btnVitamin.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnVitamin.CustomizableEdges = borderEdges5;
            this.btnVitamin.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnVitamin.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVitamin.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVitamin.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVitamin.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnVitamin.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnVitamin.ForeColor = System.Drawing.Color.White;
            this.btnVitamin.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnVitamin.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnVitamin.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnVitamin.IconMarginLeft = 11;
            this.btnVitamin.IconPadding = 10;
            this.btnVitamin.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnVitamin.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnVitamin.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnVitamin.IconSize = 25;
            this.btnVitamin.IdleBorderColor = System.Drawing.Color.Azure;
            this.btnVitamin.IdleBorderRadius = 10;
            this.btnVitamin.IdleBorderThickness = 1;
            this.btnVitamin.IdleFillColor = System.Drawing.Color.Teal;
            this.btnVitamin.IdleIconLeftImage = null;
            this.btnVitamin.IdleIconRightImage = null;
            this.btnVitamin.IndicateFocus = false;
            this.btnVitamin.Location = new System.Drawing.Point(8, 228);
            this.btnVitamin.Name = "btnVitamin";
            this.btnVitamin.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVitamin.OnDisabledState.BorderRadius = 10;
            this.btnVitamin.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVitamin.OnDisabledState.BorderThickness = 1;
            this.btnVitamin.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVitamin.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVitamin.OnDisabledState.IconLeftImage = null;
            this.btnVitamin.OnDisabledState.IconRightImage = null;
            this.btnVitamin.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnVitamin.onHoverState.BorderRadius = 10;
            this.btnVitamin.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVitamin.onHoverState.BorderThickness = 1;
            this.btnVitamin.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnVitamin.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnVitamin.onHoverState.IconLeftImage = null;
            this.btnVitamin.onHoverState.IconRightImage = null;
            this.btnVitamin.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.btnVitamin.OnIdleState.BorderRadius = 10;
            this.btnVitamin.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVitamin.OnIdleState.BorderThickness = 1;
            this.btnVitamin.OnIdleState.FillColor = System.Drawing.Color.Teal;
            this.btnVitamin.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnVitamin.OnIdleState.IconLeftImage = null;
            this.btnVitamin.OnIdleState.IconRightImage = null;
            this.btnVitamin.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnVitamin.OnPressedState.BorderRadius = 10;
            this.btnVitamin.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVitamin.OnPressedState.BorderThickness = 1;
            this.btnVitamin.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnVitamin.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnVitamin.OnPressedState.IconLeftImage = null;
            this.btnVitamin.OnPressedState.IconRightImage = null;
            this.btnVitamin.Size = new System.Drawing.Size(193, 49);
            this.btnVitamin.TabIndex = 4;
            this.btnVitamin.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnVitamin.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnVitamin.TextMarginLeft = 0;
            this.btnVitamin.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnVitamin.UseDefaultRadiusAndThickness = true;
            this.btnVitamin.Click += new System.EventHandler(this.btnVitamin_Click);
            // 
            // btnJuice
            // 
            this.btnJuice.AllowAnimations = true;
            this.btnJuice.AllowMouseEffects = true;
            this.btnJuice.AllowToggling = false;
            this.btnJuice.AnimationSpeed = 200;
            this.btnJuice.AutoGenerateColors = false;
            this.btnJuice.AutoRoundBorders = false;
            this.btnJuice.AutoSizeLeftIcon = true;
            this.btnJuice.AutoSizeRightIcon = true;
            this.btnJuice.BackColor = System.Drawing.Color.Transparent;
            this.btnJuice.BackColor1 = System.Drawing.Color.Teal;
            this.btnJuice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnJuice.BackgroundImage")));
            this.btnJuice.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJuice.ButtonText = "Nước ép";
            this.btnJuice.ButtonTextMarginLeft = 0;
            this.btnJuice.ColorContrastOnClick = 45;
            this.btnJuice.ColorContrastOnHover = 45;
            this.btnJuice.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnJuice.CustomizableEdges = borderEdges6;
            this.btnJuice.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnJuice.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnJuice.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnJuice.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnJuice.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnJuice.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnJuice.ForeColor = System.Drawing.Color.White;
            this.btnJuice.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnJuice.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnJuice.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnJuice.IconMarginLeft = 11;
            this.btnJuice.IconPadding = 10;
            this.btnJuice.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnJuice.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnJuice.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnJuice.IconSize = 25;
            this.btnJuice.IdleBorderColor = System.Drawing.Color.Azure;
            this.btnJuice.IdleBorderRadius = 10;
            this.btnJuice.IdleBorderThickness = 1;
            this.btnJuice.IdleFillColor = System.Drawing.Color.Teal;
            this.btnJuice.IdleIconLeftImage = null;
            this.btnJuice.IdleIconRightImage = null;
            this.btnJuice.IndicateFocus = false;
            this.btnJuice.Location = new System.Drawing.Point(8, 173);
            this.btnJuice.Name = "btnJuice";
            this.btnJuice.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnJuice.OnDisabledState.BorderRadius = 10;
            this.btnJuice.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJuice.OnDisabledState.BorderThickness = 1;
            this.btnJuice.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnJuice.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnJuice.OnDisabledState.IconLeftImage = null;
            this.btnJuice.OnDisabledState.IconRightImage = null;
            this.btnJuice.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnJuice.onHoverState.BorderRadius = 10;
            this.btnJuice.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJuice.onHoverState.BorderThickness = 1;
            this.btnJuice.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnJuice.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnJuice.onHoverState.IconLeftImage = null;
            this.btnJuice.onHoverState.IconRightImage = null;
            this.btnJuice.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.btnJuice.OnIdleState.BorderRadius = 10;
            this.btnJuice.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJuice.OnIdleState.BorderThickness = 1;
            this.btnJuice.OnIdleState.FillColor = System.Drawing.Color.Teal;
            this.btnJuice.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnJuice.OnIdleState.IconLeftImage = null;
            this.btnJuice.OnIdleState.IconRightImage = null;
            this.btnJuice.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnJuice.OnPressedState.BorderRadius = 10;
            this.btnJuice.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJuice.OnPressedState.BorderThickness = 1;
            this.btnJuice.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnJuice.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnJuice.OnPressedState.IconLeftImage = null;
            this.btnJuice.OnPressedState.IconRightImage = null;
            this.btnJuice.Size = new System.Drawing.Size(193, 49);
            this.btnJuice.TabIndex = 3;
            this.btnJuice.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnJuice.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnJuice.TextMarginLeft = 0;
            this.btnJuice.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnJuice.UseDefaultRadiusAndThickness = true;
            this.btnJuice.Click += new System.EventHandler(this.btnJuice_Click);
            // 
            // btnMilkTea
            // 
            this.btnMilkTea.AllowAnimations = true;
            this.btnMilkTea.AllowMouseEffects = true;
            this.btnMilkTea.AllowToggling = false;
            this.btnMilkTea.AnimationSpeed = 200;
            this.btnMilkTea.AutoGenerateColors = false;
            this.btnMilkTea.AutoRoundBorders = false;
            this.btnMilkTea.AutoSizeLeftIcon = true;
            this.btnMilkTea.AutoSizeRightIcon = true;
            this.btnMilkTea.BackColor = System.Drawing.Color.Transparent;
            this.btnMilkTea.BackColor1 = System.Drawing.Color.Teal;
            this.btnMilkTea.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnMilkTea.BackgroundImage")));
            this.btnMilkTea.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMilkTea.ButtonText = "Trà sữa";
            this.btnMilkTea.ButtonTextMarginLeft = 0;
            this.btnMilkTea.ColorContrastOnClick = 45;
            this.btnMilkTea.ColorContrastOnHover = 45;
            this.btnMilkTea.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnMilkTea.CustomizableEdges = borderEdges7;
            this.btnMilkTea.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnMilkTea.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnMilkTea.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnMilkTea.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnMilkTea.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnMilkTea.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnMilkTea.ForeColor = System.Drawing.Color.White;
            this.btnMilkTea.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMilkTea.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnMilkTea.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnMilkTea.IconMarginLeft = 11;
            this.btnMilkTea.IconPadding = 10;
            this.btnMilkTea.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnMilkTea.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnMilkTea.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnMilkTea.IconSize = 25;
            this.btnMilkTea.IdleBorderColor = System.Drawing.Color.Azure;
            this.btnMilkTea.IdleBorderRadius = 10;
            this.btnMilkTea.IdleBorderThickness = 1;
            this.btnMilkTea.IdleFillColor = System.Drawing.Color.Teal;
            this.btnMilkTea.IdleIconLeftImage = null;
            this.btnMilkTea.IdleIconRightImage = null;
            this.btnMilkTea.IndicateFocus = false;
            this.btnMilkTea.Location = new System.Drawing.Point(8, 118);
            this.btnMilkTea.Name = "btnMilkTea";
            this.btnMilkTea.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnMilkTea.OnDisabledState.BorderRadius = 10;
            this.btnMilkTea.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMilkTea.OnDisabledState.BorderThickness = 1;
            this.btnMilkTea.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnMilkTea.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnMilkTea.OnDisabledState.IconLeftImage = null;
            this.btnMilkTea.OnDisabledState.IconRightImage = null;
            this.btnMilkTea.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnMilkTea.onHoverState.BorderRadius = 10;
            this.btnMilkTea.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMilkTea.onHoverState.BorderThickness = 1;
            this.btnMilkTea.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnMilkTea.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnMilkTea.onHoverState.IconLeftImage = null;
            this.btnMilkTea.onHoverState.IconRightImage = null;
            this.btnMilkTea.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.btnMilkTea.OnIdleState.BorderRadius = 10;
            this.btnMilkTea.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMilkTea.OnIdleState.BorderThickness = 1;
            this.btnMilkTea.OnIdleState.FillColor = System.Drawing.Color.Teal;
            this.btnMilkTea.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnMilkTea.OnIdleState.IconLeftImage = null;
            this.btnMilkTea.OnIdleState.IconRightImage = null;
            this.btnMilkTea.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnMilkTea.OnPressedState.BorderRadius = 10;
            this.btnMilkTea.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMilkTea.OnPressedState.BorderThickness = 1;
            this.btnMilkTea.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnMilkTea.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnMilkTea.OnPressedState.IconLeftImage = null;
            this.btnMilkTea.OnPressedState.IconRightImage = null;
            this.btnMilkTea.Size = new System.Drawing.Size(193, 49);
            this.btnMilkTea.TabIndex = 2;
            this.btnMilkTea.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnMilkTea.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnMilkTea.TextMarginLeft = 0;
            this.btnMilkTea.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnMilkTea.UseDefaultRadiusAndThickness = true;
            this.btnMilkTea.Click += new System.EventHandler(this.btnMilkTea_Click);
            // 
            // btnCoffee
            // 
            this.btnCoffee.AllowAnimations = true;
            this.btnCoffee.AllowMouseEffects = true;
            this.btnCoffee.AllowToggling = false;
            this.btnCoffee.AnimationSpeed = 200;
            this.btnCoffee.AutoGenerateColors = false;
            this.btnCoffee.AutoRoundBorders = false;
            this.btnCoffee.AutoSizeLeftIcon = true;
            this.btnCoffee.AutoSizeRightIcon = true;
            this.btnCoffee.BackColor = System.Drawing.Color.Transparent;
            this.btnCoffee.BackColor1 = System.Drawing.Color.Teal;
            this.btnCoffee.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCoffee.BackgroundImage")));
            this.btnCoffee.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCoffee.ButtonText = "Cà phê";
            this.btnCoffee.ButtonTextMarginLeft = 0;
            this.btnCoffee.ColorContrastOnClick = 45;
            this.btnCoffee.ColorContrastOnHover = 45;
            this.btnCoffee.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnCoffee.CustomizableEdges = borderEdges8;
            this.btnCoffee.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCoffee.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCoffee.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCoffee.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCoffee.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCoffee.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCoffee.ForeColor = System.Drawing.Color.White;
            this.btnCoffee.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCoffee.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCoffee.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCoffee.IconMarginLeft = 11;
            this.btnCoffee.IconPadding = 10;
            this.btnCoffee.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCoffee.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCoffee.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCoffee.IconSize = 25;
            this.btnCoffee.IdleBorderColor = System.Drawing.Color.Azure;
            this.btnCoffee.IdleBorderRadius = 10;
            this.btnCoffee.IdleBorderThickness = 1;
            this.btnCoffee.IdleFillColor = System.Drawing.Color.Teal;
            this.btnCoffee.IdleIconLeftImage = null;
            this.btnCoffee.IdleIconRightImage = null;
            this.btnCoffee.IndicateFocus = false;
            this.btnCoffee.Location = new System.Drawing.Point(8, 63);
            this.btnCoffee.Name = "btnCoffee";
            this.btnCoffee.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCoffee.OnDisabledState.BorderRadius = 10;
            this.btnCoffee.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCoffee.OnDisabledState.BorderThickness = 1;
            this.btnCoffee.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCoffee.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCoffee.OnDisabledState.IconLeftImage = null;
            this.btnCoffee.OnDisabledState.IconRightImage = null;
            this.btnCoffee.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCoffee.onHoverState.BorderRadius = 10;
            this.btnCoffee.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCoffee.onHoverState.BorderThickness = 1;
            this.btnCoffee.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCoffee.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCoffee.onHoverState.IconLeftImage = null;
            this.btnCoffee.onHoverState.IconRightImage = null;
            this.btnCoffee.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.btnCoffee.OnIdleState.BorderRadius = 10;
            this.btnCoffee.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCoffee.OnIdleState.BorderThickness = 1;
            this.btnCoffee.OnIdleState.FillColor = System.Drawing.Color.Teal;
            this.btnCoffee.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCoffee.OnIdleState.IconLeftImage = null;
            this.btnCoffee.OnIdleState.IconRightImage = null;
            this.btnCoffee.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCoffee.OnPressedState.BorderRadius = 10;
            this.btnCoffee.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCoffee.OnPressedState.BorderThickness = 1;
            this.btnCoffee.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCoffee.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCoffee.OnPressedState.IconLeftImage = null;
            this.btnCoffee.OnPressedState.IconRightImage = null;
            this.btnCoffee.Size = new System.Drawing.Size(193, 49);
            this.btnCoffee.TabIndex = 1;
            this.btnCoffee.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCoffee.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCoffee.TextMarginLeft = 0;
            this.btnCoffee.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCoffee.UseDefaultRadiusAndThickness = true;
            this.btnCoffee.Click += new System.EventHandler(this.btnCoffee_Click);
            // 
            // btnTea
            // 
            this.btnTea.AllowAnimations = true;
            this.btnTea.AllowMouseEffects = true;
            this.btnTea.AllowToggling = false;
            this.btnTea.AnimationSpeed = 200;
            this.btnTea.AutoGenerateColors = false;
            this.btnTea.AutoRoundBorders = false;
            this.btnTea.AutoSizeLeftIcon = true;
            this.btnTea.AutoSizeRightIcon = true;
            this.btnTea.BackColor = System.Drawing.Color.Transparent;
            this.btnTea.BackColor1 = System.Drawing.Color.Teal;
            this.btnTea.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTea.BackgroundImage")));
            this.btnTea.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTea.ButtonText = "Trà";
            this.btnTea.ButtonTextMarginLeft = 0;
            this.btnTea.ColorContrastOnClick = 45;
            this.btnTea.ColorContrastOnHover = 45;
            this.btnTea.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnTea.CustomizableEdges = borderEdges9;
            this.btnTea.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTea.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTea.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTea.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTea.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTea.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTea.ForeColor = System.Drawing.Color.White;
            this.btnTea.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTea.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnTea.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTea.IconMarginLeft = 11;
            this.btnTea.IconPadding = 10;
            this.btnTea.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTea.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnTea.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTea.IconSize = 25;
            this.btnTea.IdleBorderColor = System.Drawing.Color.Azure;
            this.btnTea.IdleBorderRadius = 10;
            this.btnTea.IdleBorderThickness = 1;
            this.btnTea.IdleFillColor = System.Drawing.Color.Teal;
            this.btnTea.IdleIconLeftImage = null;
            this.btnTea.IdleIconRightImage = null;
            this.btnTea.IndicateFocus = false;
            this.btnTea.Location = new System.Drawing.Point(8, 8);
            this.btnTea.Name = "btnTea";
            this.btnTea.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTea.OnDisabledState.BorderRadius = 10;
            this.btnTea.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTea.OnDisabledState.BorderThickness = 1;
            this.btnTea.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTea.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTea.OnDisabledState.IconLeftImage = null;
            this.btnTea.OnDisabledState.IconRightImage = null;
            this.btnTea.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnTea.onHoverState.BorderRadius = 10;
            this.btnTea.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTea.onHoverState.BorderThickness = 1;
            this.btnTea.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnTea.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnTea.onHoverState.IconLeftImage = null;
            this.btnTea.onHoverState.IconRightImage = null;
            this.btnTea.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.btnTea.OnIdleState.BorderRadius = 10;
            this.btnTea.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTea.OnIdleState.BorderThickness = 1;
            this.btnTea.OnIdleState.FillColor = System.Drawing.Color.Teal;
            this.btnTea.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnTea.OnIdleState.IconLeftImage = null;
            this.btnTea.OnIdleState.IconRightImage = null;
            this.btnTea.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnTea.OnPressedState.BorderRadius = 10;
            this.btnTea.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTea.OnPressedState.BorderThickness = 1;
            this.btnTea.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnTea.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnTea.OnPressedState.IconLeftImage = null;
            this.btnTea.OnPressedState.IconRightImage = null;
            this.btnTea.Size = new System.Drawing.Size(193, 49);
            this.btnTea.TabIndex = 0;
            this.btnTea.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTea.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTea.TextMarginLeft = 0;
            this.btnTea.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTea.UseDefaultRadiusAndThickness = true;
            this.btnTea.Click += new System.EventHandler(this.btnTea_Click);
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.btnFind50);
            this.bunifuPanel2.Controls.Add(this.btnFind100);
            this.bunifuPanel2.Controls.Add(this.txtFind50);
            this.bunifuPanel2.Controls.Add(this.txtFind100);
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel2.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(1358, 70);
            this.bunifuPanel2.TabIndex = 0;
            // 
            // txtFind100
            // 
            this.txtFind100.AcceptsReturn = false;
            this.txtFind100.AcceptsTab = false;
            this.txtFind100.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.txtFind100.AnimationSpeed = 200;
            this.txtFind100.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            this.txtFind100.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.txtFind100.BackColor = System.Drawing.Color.Transparent;
            this.txtFind100.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFind100.BackgroundImage")));
            this.txtFind100.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtFind100.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFind100.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtFind100.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtFind100.BorderRadius = 1;
            this.txtFind100.BorderThickness = 1;
            this.txtFind100.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFind100.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFind100.DefaultFont = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFind100.DefaultText = "";
            this.txtFind100.FillColor = System.Drawing.Color.White;
            this.txtFind100.HideSelection = true;
            this.txtFind100.IconLeft = null;
            this.txtFind100.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFind100.IconPadding = 10;
            this.txtFind100.IconRight = null;
            this.txtFind100.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFind100.Lines = new string[0];
            this.txtFind100.Location = new System.Drawing.Point(6, 8);
            this.txtFind100.MaxLength = 32767;
            this.txtFind100.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFind100.Modified = false;
            this.txtFind100.Multiline = false;
            this.txtFind100.Name = "txtFind100";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFind100.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFind100.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFind100.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFind100.OnIdleState = stateProperties8;
            this.txtFind100.Padding = new System.Windows.Forms.Padding(3);
            this.txtFind100.PasswordChar = '\0';
            this.txtFind100.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtFind100.PlaceholderText = "Tìm chính xác món...";
            this.txtFind100.ReadOnly = false;
            this.txtFind100.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFind100.SelectedText = "";
            this.txtFind100.SelectionLength = 0;
            this.txtFind100.SelectionStart = 0;
            this.txtFind100.ShortcutsEnabled = true;
            this.txtFind100.Size = new System.Drawing.Size(585, 49);
            this.txtFind100.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtFind100.TabIndex = 0;
            this.txtFind100.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFind100.TextMarginBottom = 0;
            this.txtFind100.TextMarginLeft = 3;
            this.txtFind100.TextMarginTop = 0;
            this.txtFind100.TextPlaceholder = "Tìm chính xác món...";
            this.txtFind100.UseSystemPasswordChar = false;
            this.txtFind100.WordWrap = true;
            // 
            // txtFind50
            // 
            this.txtFind50.AcceptsReturn = false;
            this.txtFind50.AcceptsTab = false;
            this.txtFind50.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtFind50.AnimationSpeed = 200;
            this.txtFind50.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFind50.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFind50.BackColor = System.Drawing.Color.Transparent;
            this.txtFind50.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFind50.BackgroundImage")));
            this.txtFind50.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtFind50.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFind50.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtFind50.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtFind50.BorderRadius = 1;
            this.txtFind50.BorderThickness = 1;
            this.txtFind50.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFind50.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFind50.DefaultFont = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFind50.DefaultText = "";
            this.txtFind50.FillColor = System.Drawing.Color.White;
            this.txtFind50.HideSelection = true;
            this.txtFind50.IconLeft = null;
            this.txtFind50.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFind50.IconPadding = 10;
            this.txtFind50.IconRight = null;
            this.txtFind50.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFind50.Lines = new string[0];
            this.txtFind50.Location = new System.Drawing.Point(670, 8);
            this.txtFind50.MaxLength = 32767;
            this.txtFind50.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFind50.Modified = false;
            this.txtFind50.Multiline = false;
            this.txtFind50.Name = "txtFind50";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFind50.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFind50.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFind50.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFind50.OnIdleState = stateProperties4;
            this.txtFind50.Padding = new System.Windows.Forms.Padding(3);
            this.txtFind50.PasswordChar = '\0';
            this.txtFind50.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtFind50.PlaceholderText = "Tìm gần đúng món...";
            this.txtFind50.ReadOnly = false;
            this.txtFind50.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFind50.SelectedText = "";
            this.txtFind50.SelectionLength = 0;
            this.txtFind50.SelectionStart = 0;
            this.txtFind50.ShortcutsEnabled = true;
            this.txtFind50.Size = new System.Drawing.Size(612, 49);
            this.txtFind50.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtFind50.TabIndex = 1;
            this.txtFind50.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFind50.TextMarginBottom = 0;
            this.txtFind50.TextMarginLeft = 3;
            this.txtFind50.TextMarginTop = 0;
            this.txtFind50.TextPlaceholder = "Tìm gần đúng món...";
            this.txtFind50.UseSystemPasswordChar = false;
            this.txtFind50.WordWrap = true;
            // 
            // btnFind100
            // 
            this.btnFind100.ActiveImage = null;
            this.btnFind100.AllowAnimations = true;
            this.btnFind100.AllowBuffering = false;
            this.btnFind100.AllowToggling = false;
            this.btnFind100.AllowZooming = true;
            this.btnFind100.AllowZoomingOnFocus = false;
            this.btnFind100.BackColor = System.Drawing.Color.Transparent;
            this.btnFind100.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFind100.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnFind100.ErrorImage")));
            this.btnFind100.FadeWhenInactive = false;
            this.btnFind100.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnFind100.Image = global::DoAnThucTap.Properties.Resources.search_paper;
            this.btnFind100.ImageActive = null;
            this.btnFind100.ImageLocation = null;
            this.btnFind100.ImageMargin = 0;
            this.btnFind100.ImageSize = new System.Drawing.Size(66, 64);
            this.btnFind100.ImageZoomSize = new System.Drawing.Size(67, 65);
            this.btnFind100.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnFind100.InitialImage")));
            this.btnFind100.Location = new System.Drawing.Point(597, 2);
            this.btnFind100.Name = "btnFind100";
            this.btnFind100.Rotation = 0;
            this.btnFind100.ShowActiveImage = true;
            this.btnFind100.ShowCursorChanges = true;
            this.btnFind100.ShowImageBorders = false;
            this.btnFind100.ShowSizeMarkers = false;
            this.btnFind100.Size = new System.Drawing.Size(67, 65);
            this.btnFind100.TabIndex = 2;
            this.btnFind100.ToolTipText = "";
            this.btnFind100.WaitOnLoad = false;
            this.btnFind100.Zoom = 0;
            this.btnFind100.ZoomSpeed = 10;
            this.btnFind100.Click += new System.EventHandler(this.btnFind100_Click);
            // 
            // btnFind50
            // 
            this.btnFind50.ActiveImage = null;
            this.btnFind50.AllowAnimations = true;
            this.btnFind50.AllowBuffering = false;
            this.btnFind50.AllowToggling = false;
            this.btnFind50.AllowZooming = true;
            this.btnFind50.AllowZoomingOnFocus = false;
            this.btnFind50.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.btnFind50.BackColor = System.Drawing.Color.Transparent;
            this.btnFind50.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFind50.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnFind50.ErrorImage")));
            this.btnFind50.FadeWhenInactive = false;
            this.btnFind50.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnFind50.Image = global::DoAnThucTap.Properties.Resources.search_paper;
            this.btnFind50.ImageActive = null;
            this.btnFind50.ImageLocation = null;
            this.btnFind50.ImageMargin = 0;
            this.btnFind50.ImageSize = new System.Drawing.Size(66, 64);
            this.btnFind50.ImageZoomSize = new System.Drawing.Size(67, 65);
            this.btnFind50.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnFind50.InitialImage")));
            this.btnFind50.Location = new System.Drawing.Point(1288, 2);
            this.btnFind50.Name = "btnFind50";
            this.btnFind50.Rotation = 0;
            this.btnFind50.ShowActiveImage = true;
            this.btnFind50.ShowCursorChanges = true;
            this.btnFind50.ShowImageBorders = false;
            this.btnFind50.ShowSizeMarkers = false;
            this.btnFind50.Size = new System.Drawing.Size(67, 65);
            this.btnFind50.TabIndex = 3;
            this.btnFind50.ToolTipText = "";
            this.btnFind50.WaitOnLoad = false;
            this.btnFind50.Zoom = 0;
            this.btnFind50.ZoomSpeed = 10;
            this.btnFind50.Click += new System.EventHandler(this.btnFind50_Click);
            // 
            // pnlListProduct
            // 
            this.pnlListProduct.AutoScroll = true;
            this.pnlListProduct.BackColor = System.Drawing.Color.White;
            this.pnlListProduct.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlListProduct.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.pnlListProduct.Location = new System.Drawing.Point(0, 70);
            this.pnlListProduct.Name = "pnlListProduct";
            this.pnlListProduct.Size = new System.Drawing.Size(1358, 606);
            this.pnlListProduct.TabIndex = 1;
            this.pnlListProduct.WrapContents = false;
            // 
            // Product_GUI
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.ClientSize = new System.Drawing.Size(1567, 729);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.top);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Product_GUI";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Product_GUI";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.top.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.pnlMain.ResumeLayout(false);
            this.bottomLeft.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.bunifuPanel2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel top;
        private Bunifu.UI.WinForms.BunifuLabel lblData;
        private Bunifu.UI.WinForms.BunifuImageButton btnBack;
        private Bunifu.UI.WinForms.BunifuPanel bottomLeft;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFood;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnMoreDrink;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnYaour;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnIce;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnVitamin;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnJuice;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnMilkTea;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCoffee;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTea;
        private Bunifu.UI.WinForms.BunifuPanel pnlMain;
        private System.Windows.Forms.FlowLayoutPanel pnlListProduct;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuImageButton btnFind50;
        private Bunifu.UI.WinForms.BunifuImageButton btnFind100;
        private Bunifu.UI.WinForms.BunifuTextBox txtFind50;
        private Bunifu.UI.WinForms.BunifuTextBox txtFind100;
    }
}